-- Initialisation du schéma SQL pour Mon Closeur
-- Migration : 20260816000000_init_schema.sql

-- 1. Table des Entreprises (Businesses)
CREATE TABLE IF NOT EXISTS public.businesses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    owner_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Assurer la présence de la colonne owner_name si la table existait déjà
ALTER TABLE public.businesses ADD COLUMN IF NOT EXISTS owner_name TEXT;

-- Insertion de l'entreprise par défaut pour la simulation avant authentification
INSERT INTO public.businesses (id, name, owner_name)
VALUES ('00000000-0000-0000-0000-000000000000', 'Mon Closeur Default', 'Tiedrebeogo Wilfried')
ON CONFLICT (id) DO NOTHING;

-- 2. Table des Membres du Business (Business Members)
CREATE TABLE IF NOT EXISTS public.business_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE NOT NULL,
    user_id UUID NOT NULL, -- fait référence à auth.users(id)
    role TEXT NOT NULL DEFAULT 'owner',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (business_id, user_id)
);

-- 3. Table des Produits (Products)
CREATE TABLE IF NOT EXISTS public.products (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES public.businesses(id) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL,
    name TEXT NOT NULL,
    price INTEGER NOT NULL,
    category TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    stock INTEGER,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Assurer la présence des nouvelles colonnes si la table existait déjà
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS testimonials TEXT;

-- 4. Table des Zones de livraison (Delivery Zones)
CREATE TABLE IF NOT EXISTS public.delivery_zones (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES public.businesses(id) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL,
    name TEXT NOT NULL,
    fee INTEGER NOT NULL,
    delivery_time TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Table des Clients (Customers)
CREATE TABLE IF NOT EXISTS public.customers (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES public.businesses(id) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    address TEXT,
    first_contact TEXT NOT NULL,
    tags TEXT[] DEFAULT '{}'::TEXT[] NOT NULL,
    total_spent INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Table des Discussions (Conversations)
CREATE TABLE IF NOT EXISTS public.conversations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    business_id UUID REFERENCES public.businesses(id) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('ai_active', 'human_takeover', 'closed')),
    avatar TEXT NOT NULL,
    unread BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Table des Messages (Messages)
CREATE TABLE IF NOT EXISTS public.messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id INTEGER REFERENCES public.conversations(id) ON DELETE CASCADE NOT NULL,
    sender TEXT NOT NULL CHECK (sender IN ('customer', 'ai', 'human')),
    text TEXT NOT NULL,
    time TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Table des Commandes (Orders)
CREATE TABLE IF NOT EXISTS public.orders (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES public.businesses(id) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL,
    customer TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_address TEXT,
    date TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('discussing', 'confirmed', 'courier_assigned', 'sent_to_courier', 'shipping', 'delivered', 'paid', 'cancelled')),
    payment_status TEXT NOT NULL CHECK (payment_status IN ('pending', 'paid', 'overdue')),
    delivery_zone TEXT,
    shipping_fee INTEGER DEFAULT 0 NOT NULL,
    total INTEGER DEFAULT 0 NOT NULL,
    courier_name TEXT,
    chat_id INTEGER REFERENCES public.conversations(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Table des Lignes de commande (Order Items)
CREATE TABLE IF NOT EXISTS public.order_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id TEXT REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    product TEXT NOT NULL,
    quantity INTEGER DEFAULT 1 NOT NULL,
    price INTEGER NOT NULL
);

-- 10. Table des Livreurs (Couriers)
CREATE TABLE IF NOT EXISTS public.couriers (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES public.businesses(id) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    load INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. Table des Étapes de Relance (Followup Steps)
CREATE TABLE IF NOT EXISTS public.followup_steps (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES public.businesses(id) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL,
    delay_value INTEGER NOT NULL,
    delay_unit TEXT NOT NULL CHECK (delay_unit IN ('hours', 'days')),
    name TEXT NOT NULL,
    message_text TEXT NOT NULL,
    meta_template_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- SÉCURITÉ : Row Level Security (RLS)
-- ==========================================

ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.couriers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.followup_steps ENABLE ROW LEVEL SECURITY;

-- 12. Stratégies RLS de type "tenant-based" par business_id via la table business_members

DROP POLICY IF EXISTS "Allow user to manage own memberships" ON public.business_members;
CREATE POLICY "Allow user to manage own memberships" ON public.business_members
    FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Allow access by business tenant" ON public.businesses;
DROP POLICY IF EXISTS "Allow select for business tenant" ON public.businesses;
DROP POLICY IF EXISTS "Allow insert for authenticated users" ON public.businesses;
DROP POLICY IF EXISTS "Allow update for business tenant" ON public.businesses;
DROP POLICY IF EXISTS "Allow delete for business tenant" ON public.businesses;

CREATE POLICY "Allow select for business tenant" ON public.businesses
    FOR SELECT USING (
        id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        ) OR id = '00000000-0000-0000-0000-000000000000'
    );

CREATE POLICY "Allow insert for authenticated users" ON public.businesses
    FOR INSERT WITH CHECK (
        auth.uid() IS NOT NULL
    );

CREATE POLICY "Allow update for business tenant" ON public.businesses
    FOR UPDATE USING (
        id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    ) WITH CHECK (
        id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    );

CREATE POLICY "Allow delete for business tenant" ON public.businesses
    FOR DELETE USING (
        id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Allow access by business tenant" ON public.products;
CREATE POLICY "Allow access by business tenant" ON public.products
    FOR ALL USING (
        business_id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    ) WITH CHECK (
        business_id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Allow access by business tenant" ON public.delivery_zones;
CREATE POLICY "Allow access by business tenant" ON public.delivery_zones
    FOR ALL USING (
        business_id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    ) WITH CHECK (
        business_id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Allow access by business tenant" ON public.customers;
CREATE POLICY "Allow access by business tenant" ON public.customers
    FOR ALL USING (
        business_id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    ) WITH CHECK (
        business_id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Allow access by business tenant" ON public.conversations;
CREATE POLICY "Allow access by business tenant" ON public.conversations
    FOR ALL USING (
        business_id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    ) WITH CHECK (
        business_id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Allow access through linked conversation" ON public.messages;
CREATE POLICY "Allow access through linked conversation" ON public.messages
    FOR ALL USING (
        conversation_id IN (
            SELECT id FROM public.conversations 
            WHERE business_id IN (
                SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
            )
        )
    )
    WITH CHECK (
        conversation_id IN (
            SELECT id FROM public.conversations 
            WHERE business_id IN (
                SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
            )
        )
    );

DROP POLICY IF EXISTS "Allow access by business tenant" ON public.orders;
CREATE POLICY "Allow access by business tenant" ON public.orders
    FOR ALL USING (
        business_id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    ) WITH CHECK (
        business_id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Allow access through linked order" ON public.order_items;
CREATE POLICY "Allow access through linked order" ON public.order_items
    FOR ALL USING (
        order_id IN (
            SELECT id FROM public.orders 
            WHERE business_id IN (
                SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
            )
        )
    )
    WITH CHECK (
        order_id IN (
            SELECT id FROM public.orders 
            WHERE business_id IN (
                SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
            )
        )
    );

DROP POLICY IF EXISTS "Allow access by business tenant" ON public.couriers;
CREATE POLICY "Allow access by business tenant" ON public.couriers
    FOR ALL USING (
        business_id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    ) WITH CHECK (
        business_id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Allow access by business tenant" ON public.followup_steps;
CREATE POLICY "Allow access by business tenant" ON public.followup_steps
    FOR ALL USING (
        business_id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    ) WITH CHECK (
        business_id IN (
            SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
        )
    );

-- Add support for image_urls array column in products table
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS image_urls TEXT[];

-- Create storage bucket for product images if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

-- Allow public read access to product-images bucket
DROP POLICY IF EXISTS "Allow public select on product-images" ON storage.objects;
CREATE POLICY "Allow public select on product-images" ON storage.objects
    FOR SELECT USING (bucket_id = 'product-images');

-- Allow anonymous inserts to product-images bucket
DROP POLICY IF EXISTS "Allow anonymous inserts to product-images" ON storage.objects;
CREATE POLICY "Allow anonymous inserts to product-images" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'product-images');

-- Allow anonymous updates to product-images bucket
DROP POLICY IF EXISTS "Allow anonymous updates to product-images" ON storage.objects;
CREATE POLICY "Allow anonymous updates to product-images" ON storage.objects
    FOR UPDATE USING (bucket_id = 'product-images');

-- Allow anonymous deletes from product-images bucket
DROP POLICY IF EXISTS "Allow anonymous deletes from product-images" ON storage.objects;
CREATE POLICY "Allow anonymous deletes from product-images" ON storage.objects
    FOR DELETE USING (bucket_id = 'product-images');

-- Add agent_media_library JSONB column to businesses table to support send_product_visual tool URLs
ALTER TABLE public.businesses ADD COLUMN IF NOT EXISTS agent_media_library JSONB DEFAULT '{}'::jsonb;

-- Add location and contact_phone to businesses table
ALTER TABLE public.businesses ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE public.businesses ADD COLUMN IF NOT EXISTS contact_phone TEXT;

-- Create followup_runs table to log automated relances
CREATE TABLE IF NOT EXISTS public.followup_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id INTEGER REFERENCES public.conversations(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- 'silence', 'evening_order', 'next_morning'
    target_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS policies for followup_runs (allow all for business members)
ALTER TABLE public.followup_runs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow access by business tenant" ON public.followup_runs;
CREATE POLICY "Allow access by business tenant" ON public.followup_runs
    FOR ALL USING (
        conversation_id IN (
            SELECT id FROM public.conversations
            WHERE business_id IN (
                SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
            )
        )
    ) WITH CHECK (
        conversation_id IN (
            SELECT id FROM public.conversations
            WHERE business_id IN (
                SELECT business_id FROM public.business_members WHERE user_id = auth.uid()
            )
        )
    );
