-- Initialisation du schéma SQL pour Mon Closeur
-- Migration : 20260816000000_init_schema.sql

-- 1. Table des Entreprises (Businesses)
CREATE TABLE IF NOT EXISTS public.businesses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insertion de l'entreprise par défaut pour la simulation avant authentification
INSERT INTO public.businesses (id, name)
VALUES ('00000000-0000-0000-0000-000000000000', 'Mon Closeur Default')
ON CONFLICT (id) DO NOTHING;

-- 2. Table des Produits (Products)
CREATE TABLE IF NOT EXISTS public.products (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES public.businesses(id) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL,
    name TEXT NOT NULL,
    price INTEGER NOT NULL,
    category TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    stock INTEGER,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Table des Zones de livraison (Delivery Zones)
CREATE TABLE IF NOT EXISTS public.delivery_zones (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES public.businesses(id) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL,
    name TEXT NOT NULL,
    fee INTEGER NOT NULL,
    delivery_time TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Table des Clients (Customers)
CREATE TABLE IF NOT EXISTS public.customers (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES public.businesses(id) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    address TEXT,
    first_contact TEXT NOT NULL,
    tags TEXT[] DEFAULT '{}'::TEXT[] NOT NULL,
    total_spent INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Table des Discussions (Conversations)
CREATE TABLE IF NOT EXISTS public.conversations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    business_id UUID REFERENCES public.businesses(id) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('ai_active', 'human_takeover', 'closed')),
    avatar TEXT NOT NULL,
    unread BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Table des Messages (Messages)
CREATE TABLE IF NOT EXISTS public.messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id INTEGER REFERENCES public.conversations(id) ON DELETE CASCADE NOT NULL,
    sender TEXT NOT NULL CHECK (sender IN ('customer', 'ai', 'human')),
    text TEXT NOT NULL,
    time TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Table des Commandes (Orders)
CREATE TABLE IF NOT EXISTS public.orders (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES public.businesses(id) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL,
    customer TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_address TEXT,
    date TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('discussing', 'confirmed', 'courier_assigned', 'shipping', 'delivered', 'paid', 'cancelled')),
    payment_status TEXT NOT NULL CHECK (payment_status IN ('pending', 'paid', 'overdue')),
    delivery_zone TEXT,
    shipping_fee INTEGER DEFAULT 0 NOT NULL,
    total INTEGER DEFAULT 0 NOT NULL,
    courier_name TEXT,
    chat_id INTEGER REFERENCES public.conversations(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Table des Lignes de commande (Order Items)
CREATE TABLE IF NOT EXISTS public.order_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id TEXT REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    product TEXT NOT NULL,
    quantity INTEGER DEFAULT 1 NOT NULL,
    price INTEGER NOT NULL
);

-- 9. Table des Livreurs (Couriers)
CREATE TABLE IF NOT EXISTS public.couriers (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES public.businesses(id) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    load INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- SÉCURITÉ : Row Level Security (RLS)
-- ==========================================

ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.couriers ENABLE ROW LEVEL SECURITY;

-- Stratégies RLS de type "tenant-based" par business_id (simulé avec l'UUID par défaut)

CREATE POLICY "Allow access by business tenant" ON public.businesses
    FOR ALL USING (id = '00000000-0000-0000-0000-000000000000') WITH CHECK (id = '00000000-0000-0000-0000-000000000000');

CREATE POLICY "Allow access by business tenant" ON public.products
    FOR ALL USING (business_id = '00000000-0000-0000-0000-000000000000') WITH CHECK (business_id = '00000000-0000-0000-0000-000000000000');

CREATE POLICY "Allow access by business tenant" ON public.delivery_zones
    FOR ALL USING (business_id = '00000000-0000-0000-0000-000000000000') WITH CHECK (business_id = '00000000-0000-0000-0000-000000000000');

CREATE POLICY "Allow access by business tenant" ON public.customers
    FOR ALL USING (business_id = '00000000-0000-0000-0000-000000000000') WITH CHECK (business_id = '00000000-0000-0000-0000-000000000000');

CREATE POLICY "Allow access by business tenant" ON public.conversations
    FOR ALL USING (business_id = '00000000-0000-0000-0000-000000000000') WITH CHECK (business_id = '00000000-0000-0000-0000-000000000000');

-- messages n'ont pas de business_id directement, on vérifie via la conversation liée
CREATE POLICY "Allow access through linked conversation" ON public.messages
    FOR ALL USING (
        conversation_id IN (
            SELECT id FROM public.conversations 
            WHERE business_id = '00000000-0000-0000-0000-000000000000'
        )
    )
    WITH CHECK (
        conversation_id IN (
            SELECT id FROM public.conversations 
            WHERE business_id = '00000000-0000-0000-0000-000000000000'
        )
    );

CREATE POLICY "Allow access by business tenant" ON public.orders
    FOR ALL USING (business_id = '00000000-0000-0000-0000-000000000000') WITH CHECK (business_id = '00000000-0000-0000-0000-000000000000');

-- order_items n'ont pas de business_id directement, on vérifie via la commande liée
CREATE POLICY "Allow access through linked order" ON public.order_items
    FOR ALL USING (
        order_id IN (
            SELECT id FROM public.orders 
            WHERE business_id = '00000000-0000-0000-0000-000000000000'
        )
    )
    WITH CHECK (
        order_id IN (
            SELECT id FROM public.orders 
            WHERE business_id = '00000000-0000-0000-0000-000000000000'
        )
    );

CREATE POLICY "Allow access by business tenant" ON public.couriers
    FOR ALL USING (business_id = '00000000-0000-0000-0000-000000000000') WITH CHECK (business_id = '00000000-0000-0000-0000-000000000000');
